USE [master]
GO

/****** Object:  Database [Marathon_Skills_DB]    Script Date: 01.06.2020 10:24:31 ******/
CREATE DATABASE [Marathon_Skills_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Marathon_Skills_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.FIERY\MSSQL\DATA\Marathon_Skills_DB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Marathon_Skills_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.FIERY\MSSQL\DATA\Marathon_Skills_DB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Marathon_Skills_DB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Marathon_Skills_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Marathon_Skills_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Marathon_Skills_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Marathon_Skills_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Marathon_Skills_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Marathon_Skills_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Marathon_Skills_DB] SET  MULTI_USER 
GO

ALTER DATABASE [Marathon_Skills_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Marathon_Skills_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Marathon_Skills_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Marathon_Skills_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Marathon_Skills_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Marathon_Skills_DB] SET  READ_WRITE 
GO

